"""Building blocks shared by domain models.

The ownership mixin here is the mechanism behind the rule in
``docs/10-api-contracts.md``: every user-owned row is reachable only through the
authenticated user's id.
"""

from __future__ import annotations

import datetime as dt
import uuid

from sqlalchemy import DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, declared_attr, mapped_column


class TimestampMixin:
    """``created_at`` and ``updated_at``, maintained by the database."""

    @declared_attr
    def created_at(cls) -> Mapped[dt.datetime]:
        return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())

    @declared_attr
    def updated_at(cls) -> Mapped[dt.datetime]:
        return mapped_column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
            onupdate=func.now(),
        )


class UserOwnedMixin:
    """Marks a table as belonging to exactly one user.

    ``ON DELETE CASCADE`` means deleting a user removes their profile data in
    one statement rather than leaving orphans behind for a cleanup job that may
    never be written.

    The column is indexed because every query on these tables filters by it —
    an unindexed `user_id` turns each read into a sequential scan.
    """

    @declared_attr
    def user_id(cls) -> Mapped[uuid.UUID]:
        return mapped_column(
            PgUUID(as_uuid=True),
            ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )


def new_uuid_column() -> Mapped[uuid.UUID]:
    """Primary key column generated by PostgreSQL."""
    return mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
