"""add resume import pipeline

Four tables, one per data class ``docs/03-domain-model.md`` keeps separate:

- ``processing_jobs`` — the observable, retriable half of background work. The
  queue forgets a finished job; ``GOAL.md`` requires the user's view of it to
  survive, which means a row rather than an RQ id.
- ``ai_runs`` — the trace every AI feature is gated on
  (``docs/09-mvp-roadmap.md``), written for failures as well as successes.
- ``document_extractions`` — versioned AI interpretation. Never verified career
  data; a re-parse adds a version instead of overwriting one already reviewed.
- ``document_extraction_items`` — one reviewable candidate per row, carrying its
  decision and the career record it produced. That link is what makes
  confirming the same extraction twice a no-op rather than a duplicate.

Nothing here writes to the career tables. Approval goes through the career
application services, which is what ``docs/10-api-contracts.md`` means by "AI
extraction must not write verified profile data directly".

Revision ID: 3efa7771ea98
Revises: b71c4a90d2e5
Create Date: 2026-07-26
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3efa7771ea98"
down_revision: str | None = "b71c4a90d2e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=60), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failure_code", sa.String(length=40), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt >= 1", name=op.f("ck_ai_runs_attempt_positive")),
        sa.CheckConstraint("length(input_hash) = 64", name=op.f("ck_ai_runs_input_hash_length")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_runs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_runs")),
    )
    op.create_index(op.f("ix_ai_runs_input_hash"), "ai_runs", ["input_hash"], unique=False)
    op.create_index(op.f("ix_ai_runs_operation"), "ai_runs", ["operation"], unique=False)
    op.create_index(op.f("ix_ai_runs_user_id"), "ai_runs", ["user_id"], unique=False)
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("step", sa.String(length=20), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.String(length=100), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column("error_code", sa.String(length=40), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("is_retriable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_processing_jobs_attempts_not_negative")),
        sa.CheckConstraint(
            "max_attempts > 0", name=op.f("ck_processing_jobs_max_attempts_positive")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_processing_jobs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
    )
    op.create_index(
        op.f("ix_processing_jobs_entity_id"), "processing_jobs", ["entity_id"], unique=False
    )
    op.create_index(op.f("ix_processing_jobs_status"), "processing_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_processing_jobs_user_id"), "processing_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "document_extractions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("ai_run_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=60), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "warnings", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_document_extractions_version_positive")),
        sa.ForeignKeyConstraint(
            ["ai_run_id"],
            ["ai_runs.id"],
            name=op.f("fk_document_extractions_ai_run_id_ai_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_document_extractions_source_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_document_extractions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_extractions")),
        sa.UniqueConstraint(
            "source_document_id", "version", name="uq_document_extractions_version"
        ),
    )
    op.create_index(
        op.f("ix_document_extractions_source_document_id"),
        "document_extractions",
        ["source_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_extractions_user_id"), "document_extractions", ["user_id"], unique=False
    )
    op.create_table(
        "document_extraction_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("extraction_id", sa.UUID(), nullable=False),
        sa.Column("candidate_type", sa.String(length=30), nullable=False),
        sa.Column("parent_item_id", sa.UUID(), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("edited_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.SmallInteger(), nullable=True),
        sa.Column("source_text", sa.Text(), nullable=True),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("target_entity_type", sa.String(length=40), nullable=True),
        sa.Column("target_entity_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 100)",
            name=op.f("ck_document_extraction_items_confidence_range"),
        ),
        sa.CheckConstraint(
            "display_order >= 0",
            name=op.f("ck_document_extraction_items_display_order_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"],
            ["document_extractions.id"],
            name=op.f("fk_document_extraction_items_extraction_id_document_extractions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_item_id"],
            ["document_extraction_items.id"],
            name=op.f("fk_document_extraction_items_parent_item_id_document_extraction_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_document_extraction_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_extraction_items")),
    )
    op.create_index(
        op.f("ix_document_extraction_items_decision"),
        "document_extraction_items",
        ["decision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_extraction_items_extraction_id"),
        "document_extraction_items",
        ["extraction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_extraction_items_parent_item_id"),
        "document_extraction_items",
        ["parent_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_extraction_items_user_id"),
        "document_extraction_items",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_extraction_items_user_id"), table_name="document_extraction_items"
    )
    op.drop_index(
        op.f("ix_document_extraction_items_parent_item_id"), table_name="document_extraction_items"
    )
    op.drop_index(
        op.f("ix_document_extraction_items_extraction_id"), table_name="document_extraction_items"
    )
    op.drop_index(
        op.f("ix_document_extraction_items_decision"), table_name="document_extraction_items"
    )
    op.drop_table("document_extraction_items")
    op.drop_index(op.f("ix_document_extractions_user_id"), table_name="document_extractions")
    op.drop_index(
        op.f("ix_document_extractions_source_document_id"), table_name="document_extractions"
    )
    op.drop_table("document_extractions")
    op.drop_index(op.f("ix_processing_jobs_user_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_status"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_entity_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_ai_runs_user_id"), table_name="ai_runs")
    op.drop_index(op.f("ix_ai_runs_operation"), table_name="ai_runs")
    op.drop_index(op.f("ix_ai_runs_input_hash"), table_name="ai_runs")
    op.drop_table("ai_runs")
    # ### end Alembic commands ###
